@startuml
'https://plantuml.com/class-diagram

readingString <|-- Main
printOut <|-- readingString


class Main {
-Call readingString
-Call printOut
}

class readingString {
~Map<String, Integer> holder
~Scanner x
-return holder
}

class printOut {
~forloop()
~System.printf(*)
-Output
}


@enduml